site_name: ftbusiness
nav:
  - Home: 'index.md'
  - 'Fiori Tracker Business': 
      - Catalog Import: 'pages/ci/FPS01/index.md'
  - Installation: 'pages/inst.md'
  - FAQ: 'pages/faq.md'
plugins:
  - macros
extra:
  name: 'FT Business'
